
#Client Settings
[client]
	#Enables modifications of fog under lava
	enableLava = true
	#Value for fog density (0-5) Vanilla is 2.0
	#Range: 0.0 ~ 5.0
	fogDensityLava = 0.5
	#Enables modifications of fog under water
	enableWater = true
	#Value for fog density (0-5) Vanilla is 0.5 - water brightness
	#Range: 0.0 ~ 5.0
	fogDensityWater = 0.02

